"""empty message

Revision ID: 099a2d92db88
Revises: 41636af75ead
Create Date: 2019-10-15 18:36:45.961056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099a2d92db88'
down_revision = '41636af75ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qnumber', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('base_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('time_attempted', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempt_is_correct'), 'question_attempt', ['is_correct'], unique=False)
    op.create_index(op.f('ix_question_attempt_time_attempted'), 'question_attempt', ['time_attempted'], unique=False)
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('num_completed', sa.Integer(), nullable=True),
    sa.Column('num_attempted', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_index(op.f('ix_question_attempt_time_attempted'), table_name='question_attempt')
    op.drop_index(op.f('ix_question_attempt_is_correct'), table_name='question_attempt')
    op.drop_table('question_attempt')
    op.drop_table('question')
    # ### end Alembic commands ###
