"""empty message

Revision ID: 41636af75ead
Revises: 6c3b0ff4787c
Create Date: 2019-10-14 19:45:23.077822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41636af75ead'
down_revision = '6c3b0ff4787c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    # ### end Alembic commands ###
